apiVersion: v1
kind: Pod
metadata:
  name: hostaliases-pod
spec:
  restartPolicy: Never
  hostAliases:
  - ip: "127.0.0.1"
    hostnames:
    - "interop-switch.local"
    - "central-kms.local"
    - "forensic-logging-sidecar.local"
    - "centralledger.local"
    - "central-end-user-registry.local"
    - "central-directory.local"
    - "central-hub.local"
    - "centralsettlement.local"
    - "ml-api-adapter.local"
  containers:
  - name: cat-hosts
    image: busybox
    command:
    - cat
    args:
    - "/etc/hosts"	
